### ISSUE TITLE
Icon not changing after Pro upgrade

### ISSUE THREAD

**Issue by jsnelson** [XKCDY/app#51] opened 2020-08-29 17:36 UTC
I just upgraded to Pro and I tried changing the icon, but it’s not changing. I tried completely quitting the app and starting again, but it’s still the default icon on the home screen.

**Comment by codetheweb** [comment] 2020-08-29 17:41
What version of iOS are you using? Do you get an alert saying the icon was changed?
It works for me using the App Store version (aka not locally built) on iOS 14:
![RPReplay_Final1598722766](https://user-images.githubusercontent.com/7410405/91642946-f2061b80-e9f4-11ea-83f1-029bed863399.gif)

**Comment by jsnelson** [comment] 2020-08-29 17:46
I’m on iOS 13.6.1. I do get the alert though it looks different than your gif. Is the ui all SwiftUI? It might need some tweaks for 13. Or, I won’t worry about it and just wait for 14 to release.

**Comment by codetheweb** [comment] 2020-08-29 17:53
Hmm.
The alert is provided by the system, so if you get the alert the system thinks the icon has changed.
I just tried a local debug build in an iOS 13.6 simulator and it also works there, so not sure what the issue is.

I'll close this for now, if you're able to provide more details on how to reproduce it I'm happy to reopen.

**Closed** 2020-08-29 17:53 UTC
